# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f258eaf7cf4fa662b36e7bb8572332e8265bbc507d1585b2d699aed7c172f6277564e83ab2012b81c8caf87f1792f75686b7160317240abbaea0cdebc64c275

test:
  secret_key_base: 0539d3a93d95b74576218d340231531f072cf8567f6eddb07e4b5c6eaa594e6f83d207cc53c24956797b879fc0900841637d441a6d4655c14bb86ce77fc6f1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
